-- Smartcity Database Data
--
-- MySQL Script generated by MySQL Workbench
-- Sun Apr  2 12:27:15 2017
-- Model: Smartcity    Version: 1.0
-- Author: Loan Lassalle
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartcity
-- -----------------------------------------------------
USE `smartcity` ;

-- -----------------------------------------------------
-- Table `smartcity`.`RubriqueParent`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`RubriqueParent` (`nomRubriqueParent`) VALUES ('TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`RubriqueEnfant`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`RubriqueEnfant` (`idRubriqueParent`,`nomRubriqueEnfant`) VALUES (1,'TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Priorite`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Priorite` (`nomPriorite`,`niveau`) VALUES ('Mineur', 0),('Gênant', 1),('Préocupant', 2),('Important', 3),('Urgent', 4);
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Statut`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Statut` (`nomStatut`) VALUES ('TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Rue`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Rue` (`nomRue`) VALUES ('TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`NPA`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Npa` (`numeroNpa`) VALUES ('1000'),('1001'),('1002'),('1003'),('1004'),('1005'),('1006'),('1007'),('1010'),('1011'),('1012'),('1015'),('1018');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Adresse`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Adresse` (`idRue`,`numeroDeRue`,`idNpa`) VALUES (1,'1',1);
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`TitreCivil`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`TitreCivil` (`titre`,`abreviation`) VALUES ('TEST','TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Nationalite`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Nationalite` (`nomNationalite`) VALUES ('TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Sexe`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Sexe` (`nomSexe`) VALUES ('homme'),('femme');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Utilisateur`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Utilisateur` (`personnePhysique`,`avs`,`idTitreCivil`,`nomUtilisateur`,`prenom`,`dateDeNaissance`,`idSexe`,`idNationalite`,`idAdresse`,`email`,`pseudo`,`motDePasse`,`sel`) VALUES (1,'TEST',1,'TEST','TEST',NOW(),1,1,1,'TEST','TEST','TEST','TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Evenement`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Evenement` (`idRubriqueEnfant`,`idUtilisateur`,`nomEvenement`,`idAdresse`,`latitude`,`longitude`,`debut`,`details`,`idPriorite`,`idStatut`) VALUES (1,1,'TEST',1,3.14,3.14,NOW(),'TEST',1,1);
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`EvenementUtilisateur`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`EvenementUtilisateur` (`idEvenement`,`idUtilisateur`,`commentaire`) VALUES (1,1,'TEST');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`UtilisateurConfianceRubriqueEnfant`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`UtilisateurConfianceRubriqueEnfant` (`idUtilisateur`,`idRubriqueEnfant`) VALUES (1,1);
COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
