-- Smartcity Database Data
--
-- MySQL Script generated by MySQL Workbench
-- Sun Apr  2 12:27:15 2017
-- Model: Smartcity    Version: 1.0
-- Author: Loan Lassalle
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartcity
-- -----------------------------------------------------
USE `smartcity` ;

-- -----------------------------------------------------
-- Table `smartcity`.`RubriqueParent`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`RubriqueParent` (`nomRubriqueParent`) VALUES 
('trafic'),('manifestation'),('chantiers'),('doléances');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`RubriqueEnfant`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`RubriqueEnfant` (`idRubriqueParent`,`nomRubriqueEnfant`) VALUES 
(1,'accidents'),(1,'travaux'),(2,'manifestations'),(3,'rénovations'),
(3,'constructions'),(4,'doléances');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Priorite`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Priorite` (`nomPriorite`,`niveau`) VALUES 
('mineur',0),('gênant',1),('préocupant',2),('important',3),('urgent',4);
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Statut`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Statut` (`nomStatut`) VALUES 
('en attente'),('traité'),('refusé');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Rue`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Rue` (`nomRue`) VALUES 
('rue adrien-pichard'),('rue auguste-piclou'),('avenue des acacias'),('rue de l’académie'),
('avenue agassiz'),('rue de l’ale'),('avenue des alpes'),('avenue andré schnetzler'),
('avenue andré schnetzler');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`NPA`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Npa` (`numeroNpa`) VALUES 
('1000'),('1001'),('1002'),('1003'),
('1004'),('1005'),('1006'),('1007'),
('1010'),('1011'),('1012'),('1015'),
('1018');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Adresse`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Adresse` (`idRue`,`numeroDeRue`,`idNpa`) VALUES 
(1,'1',1),(1,'2',1),(1,'3',1),(1,'4',1),
(1,'5',1),(1,'6',1),(2,'7',2),(2,'8',2),
(2,'9',2),(2,'10',2),(2,'11',2),(2,'12',2),
(3,'13',5),(4,'14',5),(5,'15',2),(6,'16',6),
(7,'17',7),(8,'18',7);
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`TitreCivil`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`TitreCivil` (`titre`,`abreviation`) VALUES 
('monsieur','m'),('madame','mme'),('mademoiselle','mlle'),('docteur','dr'),
('maître','me'),('professeur','pr'),('entreprise','ent');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Nationalite`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Nationalite` (`nomNationalite`) VALUES 
('afghane'),('albanaise'),('allemande'),('belge'),
('britanique'),('canadienne'),('espagnole'),('française'),
('italienne'),('russe'),('suisse'),('turque'),
('vietnamienne');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Sexe`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Sexe` (`nomSexe`) VALUES 
('homme'),('femme');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Utilisateur`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Utilisateur` (`personnePhysique`,`avs`,`idTitreCivil`,`nomUtilisateur`,`prenom`,`dateDeNaissance`,`idSexe`,`idNationalite`,`idAdresse`,`email`,`pseudo`,`motDePasse`,`sel`) VALUES 
(1,'756.1234.5678.97',1,'lassalle','loan',CURDATE(),1,7,1,'loan.lassalle@heig-vd.ch','loan.lassalle','_smartcity_','3EgLiQyssGvABUUaqFGUZgrDKGPOlA'),
(0,NULL,7,'touring club suisse',NULL,NULL,NULL,NULL,1,'contact-tcs@tcs.ch','contact-tcs','contact-tcs','CG5bWHG0YxOvABUUaF8ra0HQvvJXr7');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Evenement`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Evenement` 
(`idRubriqueEnfant`,`idUtilisateur`,`nomEvenement`,`idAdresse`,`latitude`,`longitude`,`debut`,`fin`,`details`,`idPriorite`,`idStatut`) VALUES
-- Accidents traités
(1,2,'Entrée autoroute bloqué',1,46.52304, 6.58939,NULL,NULL,'Une voiture s\'est encastrée dans un bus',5,2),
(1,1,'Tunnel Malley fermé',1,46.52651,6.60319,NULL,NULL,'Deux voitures ont fait un frontal, le tunnel est fermé',5,2),

-- Travaux traités
(2,1,'Rond-point du Mont-D\'or',1,46.51665,6.61917,NULL,NULL,'Construction d\'un nouveau rond-point. Le trafic est ralenti. Les travaux dureront tout le mois. Les conducteurs vont devoir s\'armer de patience.',1,2),
(2,1,'Canalisations Malley',1,46.52773,6.60227,NULL,NULL,'Les canalisations doivent être refaites. Les travaux seront effectés de nuit, des nuisances sonores noctures pourraient donc déranger les personnes avec un sommeil léger.',2,2),
(2,1,'Gare Bussigny',1,46.54758,6.55193,NULL,NULL,'Des travaux sont en cours à la gare de Bussigny. Des retards et des suppresions de trains sont à prévoir. Rester vigileants.',4,2),
(2,1,'Rond-point Ouchy',1,46.50761,6.625,CURRENT_DATE() - INTERVAL 20 DAY,CURRENT_DATE() - INTERVAL 5 DAY,'Construction d\'un rond-point, trafic ralenti',2,2),
(2,1,'Rond-point géant Dapples',1,46.51514,6.62541,CURRENT_DATE(), CURRENT_DATE() + INTERVAL 6 MONTH,'Construction d\'un rond point géant, trafic ralenti',3,2),
(2,1,'Feux rouges Beaulieu',1,46.52859,6.62699,CURRENT_DATE() + INTERVAL 2 WEEK, CURRENT_DATE() + INTERVAL 3 WEEK,'Installation des Rond-point',3,2),
(2,1,'Dos d\'âne Place Chaudron',1,46.52199,6.62371,CURRENT_DATE() + INTERVAL 2 DAY, CURRENT_DATE() + INTERVAL 4 DAY,'Construction d\'un dos d\'âne avant le pont de Chauderon',2,2),
(2,1,'Petit rond-point Chailly',1,46.52669,6.65137,NULL,NULL,'Construction d\'un petit rond-point, trafic ralenti',2,2),
(2,1,'Canalisations Bellvaux',1,46.52628,6.65189,CURRENT_DATE() + INTERVAL 7 MONTH, CURRENT_DATE() + INTERVAL 8 MONTH,'Construction de nouvelles canalisations de gaz',2,2),
(2,1,'Central hydroélectrique',1,46.52125,6.6518,CURRENT_DATE(), CURRENT_DATE() + INTERVAL 2 YEAR,'Construction d\'un barrage hydroélectrique',1,2),
(2,1,'Port de Vidy',1,46.51174,6.60628,CURRENT_DATE() + INTERVAL 6 MONTH,CURRENT_DATE() + INTERVAL 11 MONTH,'Agrandissement du port de Vidy',4,2),
(2,1,'Déforestation',1,46.5353,6.62736,NULL,NULL,'Déforestation pour faire de la places',2,2),
(2,1,'Stade olympique',1,46.53318,6.62434,CURRENT_DATE() - INTERVAL 2 MONTH,CURRENT_DATE() - INTERVAL 1 MONTH,'Construction d\'un toit',1,2),

-- Travaux en attentes
(2,1,'Travaux de pavement',1,46.5223,6.63057,CURRENT_DATE() + INTERVAL 3 DAY,CURRENT_DATE() + INTERVAL 6 DAY,'Construction d\'un chemin pavé',3,1),
(2,1,'Piste d\'attérissage',1,46.54784,6.61767,CURRENT_DATE() + INTERVAL 4 MONTH,CURRENT_DATE() + INTERVAL 12 MONTH,'Construction d\'une piste d\'attérissage pour l\'A380',1,1),
(2,1,'Station de vélos de prêt',1,46.51391,6.65409,CURRENT_DATE() + INTERVAL 4 WEEK,CURRENT_DATE() + INTERVAL 8 WEEK,'Agrandissement de la station de vélos de prêt',1,1),

-- Manifestations traitées
(3,1,'WWF',1,46.52073,6.63069,NULL,NULL,'Un camps avec des tentes ont été installé par les manifestants. La circulation n\'a pas été perturbée. Sauvez les pandas !',2,2),
(3,1,'Piscine pour tous',1,46.53027,6.58497,NULL,NULL,'La piscine municipale de Renens est ouverte à tous et toutes gratuitement pour toute la journée.',1,2),
(3,1,'Concert',1,46.50691,6.62516,NULL,NULL,'Un concert est organisé à Ouchy. Plusieurs artistes vont chanter et danser toute la nuit. Venez nombreux !',1,2),
(3,1,'Anti Donald Trump',1,46.52225,6.63056,NULL,NULL,'Un cortège passera en ville pour manifester contre le président des USA',5,2),
(3,1,'Journée du vélo',1,46.56399,6.69288,CURRENT_DATE() - INTERVAL 3 DAY,CURRENT_DATE() + INTERVAL 6 DAY,'Journée Lausannoise du vélo 2017',1,2),
(3,1,'Wake up and run',1,46.52075,6.6315,NULL,NULL,'Wake up and run à Lausanne - Esplanable de Montbenon',1,2),
(3,1,'Fit & brunch',1,46.50799,6.61748,CURRENT_DATE() + INTERVAL 2 DAY,CURRENT_DATE() + INTERVAL 5 DAY,'Fit & brunch 2017 - Lausanne à table',1,2),
(3,1,'Cérémonie de remise',1,46.52438, 6.6379,NULL,NULL,'Cérémonie de remise du Prix Bibliomedia 2017',1,2),
(3,1,'Surfing dinner rallye',1,46.52261,6.63526,CURRENT_DATE() + INTERVAL 2 DAY,CURRENT_DATE() + INTERVAL 5 DAY,'Surfing dinner rallye 2017 - lausanne à table',1,2),
(3,1,'MLes puces du cpo',1,46.50863,6.62759,CURRENT_DATE() + INTERVAL 8 WEEK,CURRENT_DATE() + INTERVAL 10 WEEK, 'Désormais le CPO ouvre son espace brocante chaque semaine.',1,2),
(3,1,'Ca c\'est du jeu !',1,46.52494,6.62147,NULL,NULL,'Venez jouer en famille',1,2),
(3,1,'Les pieds dans l\'eau, la tête dans les livres',1,46.51144,6.61405,CURRENT_DATE() + INTERVAL 2 WEEK,CURRENT_DATE() + INTERVAL 3 WEEK,'Venez passer un moment de détente au milieu des livres entre deux baignades.',1,2),
(3,1,'Des livres et des brouettes',1,46.52369,6.62373,CURRENT_DATE() + INTERVAL 9 DAY,CURRENT_DATE() + INTERVAL 14 DAY,'Lecture au Parc de la Brouette',1,2),
(3,1,'A vos bobines ! - en balade',1,46.5293,6.6112,CURRENT_DATE() + INTERVAL 14 WEEK,CURRENT_DATE() + INTERVAL 17 WEEK,'Atelier autour du livre et du cinéma à l\'Esplanade du parc de Valency, en partenariat avec Les Bobines de Valency',1,2),
(3,1,'A vos bobines ! - face caméra',1,46.52029,6.62497,NULL,NULL,'Atelier cinéma au Casino de Montbenon en collaboration avec Les Bobines de Valency',1,2),
(3,1,'Apéro tricot',1,46.52021,6.63298,NULL,NULL,'Le tricot se mêle à l\'apéro au Café Chez Elle. De fil en aiguille, les verres s\'enchaînent !',1,2),
(3,1,'Ateliers chocolat',1,46.51818,6.63787,CURRENT_DATE() + INTERVAL 4 MONTH,CURRENT_DATE() + INTERVAL 5 MONTH,'Cet été, découvrez tous les secrets de fabrication du chocolat, à la Confiserie Nessi, durant leurs ateliers !',1,2),
(3,1,'Pique-nique',1,46.52024,6.62554,NULL,NULL,'Le plus célèbre des piques-niques de la ville fête le pays de la plus gourmande des manières : les pieds dans l\'herbe de Montbenon, les yeux face au Léman et le panier rempli de délectations du terroir !',1,2),

-- Manifestations en attentes
(3,1,'La famille, entre verticalité et horizontalité',1,46.52316,6.62668,CURRENT_DATE() + INTERVAL 1 MONTH,CURRENT_DATE() + INTERVAL 2 MONTH,'Une conférence sur l\'évolution de la famille par Gérard Salem',1,1),
(3,1,'Cours de sculpture et modelage',1,46.52419,6.6496,CURRENT_DATE() + INTERVAL 2 MONTH,CURRENT_DATE() + INTERVAL 3 MONTH,'Sculpture sur argile, taille de pierre tendre, plâtre, béton cellulaire…',1,1),
(3,1,'Les balades du goût ',1,46.5171,6.63235,CURRENT_DATE() + INTERVAL 10 DAY,CURRENT_DATE() + INTERVAL 20 DAY,'Les lieux emblématiques de Lausanne et les arbres de la ville. Une promenade idéale pour toute la famille !',1,1),
(3,1,'Cultive ton cocktail',1,46.52324,6.63205,CURRENT_DATE() + INTERVAL 7 DAY,CURRENT_DATE() + INTERVAL 10 DAY,'Le Pavillon Bar&Kitchen de la Riponne vous propose un atelier entre terre et verre ',1,1),
(3,1,'Imagine et dessine ton histoire',1,46.51443,6.62548,CURRENT_DATE() + INTERVAL 3 WEEK,CURRENT_DATE() + INTERVAL 4 WEEK,'Atelier kamishibaï avec le dessinateur et conteur David Telese',1,1),

-- Rénovation traitées
(4,1,'Façade de la gare',1,46.51717,6.62923,NULL,NULL,'Pour un meilleure gestion des flux de passagers',2,2),
(4,1,'Salle de fitness à la prison du Bois-Mermet',1,46.53652,6.62657,NULL,NULL,'Pour augmenter le bonheur des citoyens',2,2),

-- Rénovation en attentes
(4,1,'Eglise Saint François',1,46.51969,6.63335,CURRENT_DATE() + INTERVAL 4 MONTH,CURRENT_DATE() + INTERVAL 7 MONTH,'Pour permettre l\'arriver de pelerins',2,1),
(4,1,'Cinéma du Flon',1,46.52026,6.63102,CURRENT_DATE() + INTERVAL 10 WEEK,CURRENT_DATE() + INTERVAL 17 WEEK,'Pour des fauteils allongés !',1,1),

-- Constructions traitées
(5,1,'Site de minage Bitcoin',1,46.52634,6.63606,NULL,NULL,'Construction d\'un batiment pour le minage de bitcoin',2,2),

-- Constructions en attentes
(5,1,'Usine Tesla',1,46.51662,6.60171,CURRENT_DATE() + INTERVAL 10 DAY,CURRENT_DATE() + INTERVAL 20 DAY,'Construction d\'une usine de batterie pour l\'entreprise Tesla',2,1),
(5,1,'Site de lancement de fusée Falcon 9',1,46.51129,6.61522,CURRENT_DATE() + INTERVAL 1 MONTH,CURRENT_DATE() + INTERVAL 2 YEAR,'Construction d\'un site de lancement de fusée Falcon 9 et Falcon Heavy',2,1),

-- Doléances traitées
(6,1,'Banc cassé',1,46.51716,6.60333,NULL,NULL,'Le banc en bois a été scié en deux',2,2),
(6,1,'Cabine téléphone HS',1,46.52322,6.63256,NULL,NULL,'Une personne mal intentionnée a arraché le téléphone de la cabine',2,2),

-- Doléances en attentes
(6,1,'Passage des éboueurs',1,46.51855,6.63395,NULL,CURRENT_DATE() + INTERVAL 1 DAY,'Les poubelles débordent !!',5,1),
(6,1,'Connexion à la fibre optique',1,46.52153,6.62849,NULL,CURRENT_DATE() + INTERVAL 1 MONTH,'Pour plus de compétitivités, la fibre optiques est nécessaire !',3,1);
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Commentaire`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Commentaire` (`idEvenement`,`idUtilisateur`,`commentaire`) VALUES 
(1,1,'début de l\'accident approximatif');
COMMIT;

-- -----------------------------------------------------
-- Table `smartcity`.`Confiance`
-- Dumping data
-- -----------------------------------------------------

SET AUTOCOMMIT=0;
INSERT INTO `smartcity`.`Confiance` (`idUtilisateur`,`idRubriqueEnfant`) VALUES 
(1,1),(1,2);
COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
